variables:
  SampleName: FFX_CACAO_Sample
  SolutionDirDX12: sample\build\DX12
  GIT_SUBMODULE_STRATEGY: normal

before_script:
  - 'for /f "usebackq delims=" %%i in (`vswhere.exe  -products Microsoft.VisualStudio.Product.BuildTools -property installationPath`) do set MSBUILD_PATH=%%i'
  - 'call "%MSBUILD_PATH%\VC\Auxiliary\Build\vcvars64.bat"'
  - 'cd sample\build'
  - 'call GenerateSolutions.bat -T v141'
  - 'cd ..\..'

stages:
  - build
  - deploy

build d3d12 sample release:
  tags:
  - windows
  - amd64
  stage: deploy
  except:
  - tags
  script:
  - echo Building "%SampleName%_DX12.sln"
  - cd %SolutionDirDX12%
  - 'msbuild.exe "%SampleName%_DX12.sln" /p:Configuration=Release /p:Platform=x64'
  - cd ../../..
  - mkdir %SampleName%
  - move sample/bin %SampleName%
  - move sample/media %SampleName%
  - move NOTICES.txt %SampleName%
  - echo cd .\%SampleName%\bin\ > %SampleName%_DX12.bat
  - echo start %SampleName%_DX12.exe >> %SampleName%_DX12.bat
  artifacts:
      name: "%SampleName%-%CI_COMMIT_REF_NAME%-%CI_COMMIT_SHORT_SHA%"
      paths:
      - "%SampleName%/bin/"
      - "%SampleName%/media/"
      - "%SampleName%/NOTICES.txt"
      - "%SampleName%_DX12.bat"
      - "readme.md"

build d3d12 sample release tagged:
  tags:
  - windows
  - amd64
  stage: deploy
  only:
  - tags
  script:
  - echo Building "%SampleName%_DX12.sln"
  - cd %SolutionDirDX12%
  - 'msbuild.exe "%SampleName%_DX12.sln" /p:Configuration=Release /p:Platform=x64'
  - cd ../../..
  - mkdir %SampleName%
  - move sample/bin %SampleName%
  - move sample/media %SampleName%
  - move NOTICES.txt %SampleName%
  - echo cd .\%SampleName%\bin\ > %SampleName%_DX12.bat
  - echo start %SampleName%_DX12.exe >> %SampleName%_DX12.bat
  artifacts:
      name: "%SampleName%-%CI_COMMIT_TAG%"
      paths:
      - "%SampleName%/bin/"
      - "%SampleName%/media/"
      - "%SampleName%/NOTICES.txt"
      - "%SampleName%_DX12.bat"
      - "readme.md"
